### ISSUE TITLE
Getting there... but not connecting. Thread Start........

### ISSUE THREAD

**Issue by WilsonBradley** [jwechrs/virtual-rd#1] opened 2020-06-11 19:03 UTC
Within Oculus Quest. When connecting to a RealVNC server by entering, within Quest, the address and port , the response is Thread Start... nothing happens. Not sure what this means.
Able to connect using different devices without a problem.

**Comment by WilsonBradley** [comment] 2020-06-11 19:03
Are there documentations anywhere?

**Comment by jwechrs** [comment] 2020-06-12 10:54
Thank you for your feedback. Could you provide the following information?

**VNC server OS and version** (e.g. macOS 10.15.3/Ubuntu 20.04)
**VNC server name and version** (e.g. RealVNC 6.7.2)
**Additional context** 
- Devices that were able to connect successfully
- Options for VNC server (command line options if any)

While this app is intended for Oculus Go, the basic functionality should work fine on Oculus Quest too.
Unfortunately I do not have other documents at this point (other than this repository).

**Comment by WilsonBradley** [comment] 2020-08-09 18:47
Using Tightvnc server on linux. Please provide proper syntax / instructions to connected to a TightVNC server.
Never successful , always get "Network error occurred. VNC server hostname: " . Doesn't mean much . Able to connect viewer via Android Phone or PC no problems. Lacking proper instructions / documents/ syntax to get started

**Comment by jwechrs** [comment] 2020-08-11 12:10
I am glad to hear it worked. Also, thank you for your feedback.
1,2) I will consider this in the future release.
3) Not at the moment, as VNC protocol itself does not support audio.
4) You can connect to VNC server via USB. Please see [this page](https://jwechrs.github.io/virtual-rd/docs/connection.html#vnc-connection-over-usb) for more detail. 
5) Thank you for reporting, I will try to reproduce it. It would be highly appreciated if you could provide logcat (`adb logcat|grep Unity`) when the app crashes.

**Comment by WilsonBradley** [comment] 2020-08-26 04:19
Thank you so much for the response. 
Will try and capture the logcat and share when it crashes.

Any hope for next version being able to save network connection history to easily reconnect?

Still have not been able to get a reverse USB connection. When running adb command, it says
error: insufficient permissions for device: user in plugdev group; are your udev rules wrong?

Thanks

**Comment by WilsonBradley** [comment] 2020-08-26 15:02
After some research added this , but not sure the idVendor is correct for Quest device. 
![image](https://user-images.githubusercontent.com/8173893/91320511-3db18e80-e783-11ea-9ca3-33d69698896f.png)

**Comment by WilsonBradley** [comment] 2020-08-26 15:20
Much closer now, the above idVendor is correct 2833 for Quest , they changed it recently (for some reason)
After accepting Raspberry Pi key within Quest while USB connected, seems to have gotten farther, no errors.
![image](https://user-images.githubusercontent.com/8173893/91322673-a0a42500-e785-11ea-879e-b0760554a339.png)
Now, just need to figure out how to launch TightVNC within Raspian using USB pipe.

**Comment by WilsonBradley** [comment] 2020-08-26 15:31
Got tightVNC connected using USB successfully by using;
 host name: 127.0.0.1, port: 5901 (The port varies depending on your config, mine is 5901)

![com tn VRD-20200826-101009](https://user-images.githubusercontent.com/8173893/91324110-4c9a4000-e787-11ea-83da-7f4d8df76fd1.jpg)

**Comment by WilsonBradley** [comment] 2020-08-26 15:35
Now need to add 5901 port route to USB at startup.

**Comment by WilsonBradley** [comment] 2020-08-26 16:12
You can add Raspian on Raspberry Pi 
![image](https://user-images.githubusercontent.com/8173893/91328773-f5976980-e78c-11ea-9e21-063646a50bb8.png)

**Comment by jwechrs** [comment] 2020-08-27 13:01
Thank you for the update. I included TightVNC on Raspberry pi in the document page.
I will close this issue, as the connection problem has been resolved.
I am implementing the network connection history feature for the future release.

**Closed by jwechrs** 2020-08-27 13:01 UTC

**Comment by WilsonBradley** [comment] 2020-09-02 17:15
Ok , you might also mention specifically to Raspberry Pi servers using comm through USB, they will need to add a device file for Quest. 
 sudo nano /etc/udev/rules.d/51-android.rules

add this into new file;
SUBSYSTEM=="usb", ATTR{idVendor}=="2833", MODE="0666". GROUP="plugdev"

**Comment by WilsonBradley** [comment] 2020-09-02 20:48
I tested it by disconnecting wifi completely on Quest and it works. ;-)
